[env]
platform = espressif32 @ 6.5.0 
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    PubSubClient@ 2.8.0
    m5stack/M5GFX @ 0.1.17       
    m5stack/M5Unified @ 0.1.17 
    lvgl/lvgl @ 9.4.0
    bblanchon/ArduinoJson @ 7.2.2

[env:release]
build_type = release
build_flags =
    -DCORE_DEBUG_LEVEL=5
    -O0
    -DLV_CONF_INCLUDE_SIMPLE
    -I src
    -DLGFX_LVGL_VERSION_MAJOR=9
extra_scripts = post:generate_user_custom.py
custom_firmware_version = 0.0.2
custom_firmware_name = K024_Demoboard_JIE_20230913
custom_firmware_suffix = .bin
custom_firmware_dir = ./